require 'json'
require 'shoryuken'
require_relative 'micro/messages/inbound'
require_relative 'micro/messages/outbound'
require_relative 'micro/geo_locator'
require_relative 'micro/outbound_message_sender'
